### ISSUE TITLE
Node version aliases interpeted as command

### ISSUE THREAD

**Issue by AdrieanKhisbe** [ehmicky/nve#19]
-  **Bug Description**:  non [whitelisted aliases](https://github.com/ehmicky/nve/blob/master/src/parse.js#L67) are interpreted as command
- **Steps to reproduce**
  1. install nve@12
  2. run `nve 12 default node  --version`

- **Expected behavior**: node version being outpted for node  12, and nvm `default`  node version
- **Current behavior**: Crash interpreting `default` as the command:
   ```
    $ nve 10 default node --version
    spawn default ENOENT
    ```
- **Configuration**: none  specific
- **Environment**: <details>
   <pre>
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Memory: 3.38 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.19.1 - ~/.nvm/versions/node/v8.16.2/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
  Browsers:
    Chrome: 81.0.4044.113
    Safari: 13.1
  npmGlobalPackages:
    nve: 12.0.0
   </pre>
 </details>

- **Can you submit a pull request?**: **Yes**,  but it's better to agree what is best strategy to address the issue.

- **Possible options to solve this problem** _(probably non exhaustive)_:
  1.  prefix the aliases with some _special_ character, so that they are not interpreted as commands.
      - `:` could do the trick
      - **example**: `nve 12 :default node  --version`
  2. use an optional separator to separate versions from commands, something similar to `--` with flags
     - `:` could work too
     - **example**: `nve 12 default : node  --version`
  3. checking if nve arg is resolvable to a node version or if it's a bash available command

I would rather go for option 1 or 2.  And possibly both as the two command syntax are not incompatible.
Tell me what  you think about it @ehmicky :)

**Comment by ehmicky** [comment]
Hi again, thanks a lot for reaching out!

A third option could be separating versions with `,` instead of spaces: ` nve 12,default,10 node --version`. It might also help users separate visually the versions from the command and arguments.

All aliases (including nvm custom aliases) are supported when using `nve now`. But aliases passed directly to `nve` itself are currently limited to `now`, `latest` and `lts` to keep it simple. New aliases can be added though if it turns out they are useful.

Apart from `default` and `node` (which `nve` calls `latest`), are there any other instances of nvm custom aliases that you would find useful when combined with `nve`?

**Comment by AdrieanKhisbe** [comment]
Separating with comma is indeed another option that would work too!
And it might be simpler to implement that the two first options I proposed, and potentially with less edge cages.

About the alias that should be supported of their own, I see `current` and the `lts`(and `lts/...` ones)
(I doubt `node` alias itself to be useful, `nve  node node --version` feeling a bit confusing).

If we go for the comma separated version you suggest, _- which I like more and more thinking about it -_ we could have an implementation that **support leading or trailing `,`**, so that `nve my-custom-hypothetetical-alias, node --version` does not need whitelisting. (kind of syntax used for tuple of one element in python)

I'm in to implement that option if you think it's the best approach. :)

_(PS: I guess you that by `nve now` you meant `nve here`, am I right?)_

**Comment by ehmicky** [comment]
I have just comma separation with [`nve@13`](https://github.com/ehmicky/nve/releases/tag/13.0.0). 

I have also added a new alias `global` which should give you the global Node.js version regardless of the current directory. If you use `nvm`, this will be the same as `nvm current`. Unless you have run `nvm use` in the current session, this will also be the same as the `default` nvm alias. I have renamed `here` to `local` to contrast with `global`. More details [here](https://github.com/ehmicky/nve#usage).

About trailing `,` what would be the goal: allowing aliases with commas inside their names?

The `lts` alias (called `lts/*` in nvm) is currently supported to target the latest LTS version. 

Now I have some reserved about adding support to the following:
  - `lts/boron`, etc.: I think using the release number is much simpler and I don't see a strong reason to use the LTS release name instead.
  - user-defined aliases: `current`, `default`, `lts/*` and `node`/`stable` (`latest`) can be useful. But I am completely sure of the usefulness of user-defined aliases. I would favor "less is more" and only adding support for them if there is a strong use case for them.

**Comment by AdrieanKhisbe** [comment]
I just gave a try, and had this:
```bash
$ npx nve@13 default,8,12 node --version
Not a valid Node version range: default
```

I was assuming that every part of the comma separated version range would be implicitely considered as an alias that should be tried to be resolved. That's why I suggested possibility to support trailing comma `nve default, node  --version`  to force consider `default` as an alias.

It would not be necessary if the **first non flag argument of  `nve`** is automatically **considered as a legit version** (or set of comma separated version).
That way, `normalize-node-version` support of aliases would just handle alias resolving, and `nve`  won't need custom logic regarding what could be an alias.

**Comment by ehmicky** [comment]
What I meant above is that `default` is intentionally not allowed as an alias. In order to keep `nve` simple, I would like to only allow version ranges and a limited amount of aliases after the `nve` command. Those aliases are currently `latest`, `lts`, `global` and `local`, but could be extended if there is a strong use case.

On the other hand, the `local` alias allow using any alias (including `default`) when that alias is inside a `.nvmrc`. The rational here is that `local` is meant to be backward-compatible with any Node.js version manager.

So the reason `nve default,8,12 node --version` fails is not due to CLI flags parsing but to the fact that `default` is not currently allowed to be passed to `nve`. While `global` has a slightly different behavior, I think it should cover most cases where users might want to use `default` instead. My assumption is that what you are actually trying to do is using the global Node.js version.

**Comment by AdrieanKhisbe** [comment]
Clarification: I said _parsing_ because that's [were happens the logic in nve `parse.js#isVersion`](https://github.com/ehmicky/nve/blob/master/src/parse.js#L64-L66).

------

When I proposed to add **nvm alias support to normalize-node-version** (cf https://github.com/ehmicky/normalize-node-version/pull/3), that was only so it **could be used in `nve`**.

Also this issue, to which command separation came up a possible solution, was only so I could use some nvm alias with `nve`. (as stated in the [original message in the issue](https://github.com/ehmicky/nve/issues/19#issue-605116898)). `default` was used to illustrate mainly because it's the more classic and standard `nvm` alias.

To me supporting a comma separated list of version ranges adds more complexity to `nve` than implicitely consider first argument as a version range.
Besides there is no value added if its parts are not considered as valid `normalize-node-version` version ranges. Without that it's only cosmetics: `nve 10,12 npm run whatever` over `nve 10 12 npm run whatever`

**Comment by ehmicky** [comment]
> When I proposed to add nvm alias support to normalize-node-version (cf ehmicky/normalize-node-version#3), that was only so it could be used in nve.
> Also this issue, to which command separation came up a possible solution, was only so I could use some nvm alias with nve.

Just to make sure we're talking about the same thing: you are saying your core problem is being able to use nvm aliases with `nve`, for example `nve myAlias`, did I understand this correctly?

**Comment by AdrieanKhisbe** [comment]
Exactly =)

**Comment by ehmicky** [comment]
I am not quite convinced that nvm user-defined aliases are useful. I think they just add complexity. Do you have an example where they could be useful instead of just typing the Node.js version directly?

Note that I am talking of user-defined aliases, not of `default`, `node`, `stable`, `current`, `lts/*`.

**Comment by ehmicky** [comment]
Closing this issue as stale.
