### ISSUE TITLE
Run all versions specified in `engines.node`

### ISSUE THREAD

**Issue by ericcornelissen** [ehmicky/nve#38]
### Guidelines

- [X] Please search other issues to make sure this feature has not already been requested.

### Which problem is this feature request solving?

I started using nve to run tests and all Node.js version supported by a library I maintain. The library specifies the supported Node.js versions in `package.json` as:

```json
"engines" {
  "node": "^10.13.0 || ^12 || ^14 || ^16 || ^18 || ^19 || ^20"
},
```

and I would like `nve` to run against each of these versions when using `nve local`. Instead, as of v16.0.0, `nve local node --version` would run only on Node.js `20.X.Y`.

### Describe the solution you'd like

For my particular use case running each version separated by a `||` would suffice.

However, I'm not sure that solution works well in the generalized case (for all valid values of `engines.node`). For example, if `"node": "^18 || ^20"` runs on both Node.js v18 and v20, then what should `"node": ">=18"` do? Run only Node.js v20, or also v18 (and v19)?

### Pull request (optional)

- [ ] I can submit a pull request.

**Comment by ehmicky** [comment]
Hi @ericcornelissen,

Thanks for sharing this idea.

I think it's a very valid use case. For example, many people want to run their tests locally using the different major releases of Node.js that they support, as specified in `package.json` `engines.node`.

However, there are quite a few challenges to implementing this. The first is that `engines.node` is a version range, which is slightly different from a list of versions. Interpreting the former as the latter leaves some room for ambiguity, including the one you are mentioning with `>=18` resolving either to `18,20` or to `18,19,20`. I can see some other more complex version ranges where the user's intent might not be straightforward.

Another issue is that `nve` (and the ~10 modules that support it) currently interprets each version field as a single version. A single field like `nve package.json ...` could conceptually expand to multiple versions, but this would require some rather big work on the whole code base. It is totally feasible, but it is an implementation cost that needs to be taken into account.

Also, some users might want to keep the current behavior where `engines.node` resolves to a single version. This means a new boolean flag (or something like that) would need to be added. One of the design goals of `nve` is simplicity, so I am quite mindful about adding new options.

Based on this, I think the best might be to implement this logic on top of `nve` instead of inside `nve`. For example, using some shell script parsing `package.json`. This could be its own Node module too. 

Otherwise, a workaround could be to manually input the versions from `package.json` to the `nve` command. While having a way to automatically do this and prevent that duplication is definitely nice, I might be too concerned about the above points to implement this.

That being said, thanks a lot for sharing this!

**Comment by ericcornelissen** [comment]
Thanks for elaborating @ehmicky, that makes total sense :slightly_smiling_face:

**Comment by balupton** [comment]
For what it's worth, https://github.com/bevry/testen does this. #44 has some details on how
