### ISSUE TITLE
Self-contained CLI (package it, no need to have node installed)

### ISSUE THREAD

**Issue by tunnckoCore** [ehmicky/nve#4]
Because, yes, you usually will have node installed anyway, but I think it will be useful to be able to don't depend on having nodejs. For example, you can package it using `pkg` or `ncc` or something like them.

So in environments that can't/don't have nodejs, they can just download the `nve` and use it.

**Comment by ehmicky** [comment]
Thanks for the suggestion @tunnckoCore.

I thought of it when I built this but there are three issues:  
  1) What about npm? If the user hasn't installed Node.js, they haven't installed npm either. Without npm, they could not run any Node.js code that has dependencies, unless the dependencies are bundled.
  2) Environments without Node.js installed are most likely happening in CI or production. In those types of environments (as opposed to a dev/local environment), there is more likelihood that only one Node.js version needs to be run. If so, it would be simpler and faster to download the Node.js executable directly from `nodejs.org` instead of downloading a `nve` package from GitHub.
  3) This project is aimed at one-off/single Node.js execution. Global or project-wise Node.js installation is a separate problem as it introduces different problems and developer experience needs. Projects like `nvm` are better suited for this. I am thinking that packaging `nve` as a self-contained binary is encouraging using it as a global Node.js, which it is not designed for.

What do you think?

**Comment by tunnckoCore** [comment]
Agree. When thinking it, it really makes sense not to.

**Comment by ehmicky** [comment]
No worries, that was a very valid question.

@all-contributors please add @tunnckoCore for suggesting interesting ideas.
