### ISSUE TITLE
Show progress bar downloading

### ISSUE THREAD

**Issue by Hongarc** [ehmicky/nve#6]
In first time download new node.js version, it is so tedious, just black screen.

Let user know that `nve` is downloading node.js(I thought I type wrong command)

**Comment by ehmicky** [comment]
Hi #Hongarc, great idea!

I've just added it in the latest release `1.2.2`.

When downloading a new Node.js version, a spinner is now showing the number of megabytes downloaded so far. 

Unfortunately it's a little hard to show the percentage as a progress bar because `nodejs.org` does not send any `Content-Length` response header. I could download each binary's length in advance and hard-code it, but that's lots of logic that I would prefer not to maintain.

However the spinner might just do the trick, let me know what you think!

The spinner can be disabled using the `NVE_PROGRESS=0` environment variable.

@all-contributors please add @Hongarc for suggesting this idea that should improve the developer experience.

**Comment by ehmicky** [comment]
The latest major release [`3.0.0`](https://github.com/ehmicky/nve/releases/tag/3.0.0) has added the `--no-progress` option which replaces the `NVE_PROGRESS` environment variable.

**Comment by ehmicky** [comment]
Correction: `nodejs.org` does send the `Content-Length`. I have updated the spinner to show the download percentage in [`3.4.0`](https://github.com/ehmicky/nve/releases/tag/3.4.0).

In a future release I will replace the percentage spinner with a progress bar.

**Comment by ehmicky** [comment]
A progress bar is now used instead of a spinner since [`5.0.0`](https://github.com/ehmicky/nve/releases/tag/5.0.0).
